# Generated by Django 3.2.4 on 2021-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210624_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Content')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('image', models.ImageField(upload_to='banner_images', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
    ]
