# Generated by Django 3.2.4 on 2021-07-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
