# Generated by Django 3.2.4 on 2021-07-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_table'),
        ('main', '0009_auto_20210706_0715'),
    ]

    operations = [
    ]
