# Generated by Django 3.2.4 on 2021-07-13 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210712_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='released',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Released'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sells',
            field=models.IntegerField(default=0, verbose_name='Sells'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='Free shipping'),
        ),
    ]
