# Generated by Django 3.2.4 on 2021-07-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210713_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shop', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(verbose_name='Discount percentage'),
        ),
    ]
