# Generated by Django 3.2.4 on 2021-07-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_discount_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='patronymic'),
        ),
    ]
