# Generated by Django 3.2.4 on 2021-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_discount_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Sort index'),
        ),
    ]
