# Generated by Django 3.2.4 on 2021-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profile_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
    ]
