# Generated by Django 3.2.4 on 2021-07-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_sort_index'),
        ('main', '0018_auto_20210723_1337'),
    ]

    operations = [
    ]
