# Generated by Django 3.2.4 on 2021-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210727_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='patronymic'),
        ),
    ]
