# Generated by Django 3.2.4 on 2021-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210804_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
