# Generated by Django 3.2.4 on 2021-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='icons/user_icon.png', null=True, upload_to='users_photos/%Y/%m/%d', verbose_name='photo'),
        ),
    ]
