# Generated by Django 3.2.4 on 2021-08-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_0017_product_sort_index_0018_auto_20210723_1337'),
        ('main', '0024_alter_profile_photo'),
    ]

    operations = [
    ]
