# Generated by Django 3.2.4 on 2021-08-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_20210731_1611'),
        ('main', '0025_merge_20210804_1143'),
    ]

    operations = [
    ]
