# Generated by Django 3.2.4 on 2021-08-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_20210804_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='category_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/', verbose_name='Image'),
        ),
    ]
