# Generated by Django 3.2.4 on 2021-08-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_discount_title'),
        ('main', '0027_auto_20210806_0630'),
    ]

    operations = [
    ]
