# Generated by Django 3.2.4 on 2021-08-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_0024_discount_title_0027_auto_20210806_0630'),
    ]

    operations = [
    ]
