# Generated by Django 3.2.4 on 2021-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_merge_0024_discount_title_0027_auto_20210806_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text_error',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='text_error'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='icons/user_icon.png', null=True, upload_to='users_photos/%Y/%m/%d', verbose_name='photo'),
        ),
    ]
