# Generated by Django 3.2.4 on 2021-08-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210818_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
    ]
