# Generated by Django 3.2.4 on 2021-08-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_profile_photo'),
        ('main', '0029_merge_20210810_1822'),
        ('main', '0030_auto_20210818_0944'),
    ]

    operations = [
    ]
