# Generated by Django 3.2.4 on 2021-08-25 12:55

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_merge_20210824_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=main.models.import_directory_path, verbose_name='File')),
                ('mail', models.EmailField(help_text='(Enter the mail to which the notification about the end of import will be sent)', max_length=100, verbose_name='Mail')),
                ('status', models.CharField(default='Not started', max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='recentproduct',
            options={'verbose_name': 'Recent Product', 'verbose_name_plural': 'Recent Products'},
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='price',
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='base_price',
            field=models.FloatField(default=2.0, verbose_name='base_price'),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='extra_price',
            field=models.FloatField(default=5.0, verbose_name='extra_price'),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='free_shipping_threshold',
            field=models.FloatField(default=15.0, verbose_name='free_shipping_threshold'),
        ),
        migrations.AddField(
            model_name='order',
            name='tm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation time'),
            preserve_default=False,
        ),
    ]
